# https://github.com/crate-ci/typos/blob/master/docs/reference.md
# https://github.com/crate-ci/typos/blob/master/docs/design.md#identifiers-and-words

# try adding to `identifiers` list first, if doesn't work then `words` list

[default.extend-identifiers]
BigSur = "BigSur"
mak = "mak"
UPnP = "UPnP"

[default.extend-words]
AFE = "AFE"
